### ISSUE TITLE
Refactor setup.py into pyproject.toml

### ISSUE THREAD

**Issue by MyPyDavid** [MarcoReidelbach/MaRDMO-Plugin#52]
The `setup.py` file for configuring the package is outdated (even though still used) and the `pyproject.toml` is preferred, also for the `rdmo-plugins-..` we use `pyproject.toml` (https://github.com/rdmorganiser/rdmo-plugins-zenodo/blob/main/pyproject.toml).

Locally I refactored it into something like this:

```toml
[project]
name = "mardmo_export_plugin"
version = "0.1"
description = "Plugin to document and query interdisciplinary workflows using the MaRDI Portal."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "Apache-2.0" }

# Author and maintainer information
authors = [
    { name = "Marco Reidelbach (MaRDI TA4)", email = "reidelbach@zib.de" }
]
maintainers = [
    { name = "Marco Reidelbach (MaRDI TA4)", email = "reidelbach@zib.de" }
]

# Project dependencies
dependencies = [
    "rdmo>=2.1.3",
    "bibtexparser",
    "langdetect",
    "pylatexenc",
    "wikibaseintegrator"
]

# Classifiers provide metadata about the project
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10"
]


# URLs related to the project
[project.urls]
Repository = "https://github.com/MarcoReidelbach/MaRDMO" 

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests", "tests.*"]

# # Specify package data to include
# [tool.setuptools.package-data]
# "MaRDMO" = [
#     "templates/MaRDMO/*.html",
#     "templates/MaRDMO/*.md",
#     "templates/MaRDMO/*.mediawiki",
#     "data/*.json"
# ]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

```
